B2BCHCKOUT-10
vtex-apps/b2b-checkout-settings pull request #10
Opened 2022-02-01 14:19 UTC by arturmagalhaesjr

Created a quote button which goes to /b2b-quote/create flow

2022-02-01 17:45 UTC, wender requested changes

2022-02-01 17:45 UTC, wender commented on checkout-ui-custom/checkout6-custom.js
> +      createQuoteButtonLabel: 'Criar uma Cota',
Criar uma Cotação

2022-02-03 17:52 UTC, arturmagalhaesjr reviewed
Done

2022-02-03 18:33 UTC, polishq requested changes
I think we want to add this button conditionally, perhaps via a toggle in the settings, since the account may or may not have the quotes app installed.

2022-02-04 20:49 UTC, arturmagalhaesjr reviewed
done

2022-02-04 21:03 UTC, arturmagalhaesjr reviewed
Done

2022-02-18 19:40 UTC, polishq submitted a review, later dismissed

2022-02-18 19:42 UTC, wender submitted a review, later dismissed

2022-02-18 19:55 UTC, merged